# https://taskfile.dev

version: "3"

includes:
  git:
    taskfile: ./node_modules/@northbridge-security/ai-toolkit/tasks/git.yml
    dir: .
  json:
    taskfile: ./node_modules/@northbridge-security/ai-toolkit/tasks/json.yml
    dir: .
  yaml:
    taskfile: ./node_modules/@northbridge-security/ai-toolkit/tasks/yaml.yml
    aliases:
      - yml
    dir: .
  markdown:
    taskfile: ./node_modules/@northbridge-security/ai-toolkit/tasks/markdown.yml
    aliases:
      - md
    dir: .
  security:
    taskfile: ./node_modules/@northbridge-security/ai-toolkit/tasks/security.yml
    aliases:
      - s
    dir: .
  op:
    taskfile: ./node_modules/@northbridge-security/ai-toolkit/tasks/onepassword.yml
    dir: .

vars:
  PROJECT_NAME: "mmd"

tasks:
  install:
    desc: "Install/upgrade required development tools"
    aliases: [i]
    silent: true
    cmds:
      - |
        set -euo pipefail

        GREEN='\033[0;32m'
        YELLOW='\033[0;33m'
        CYAN='\033[0;36m'
        RED='\033[0;31m'
        NC='\033[0m'

        echo -e "${CYAN}Installing Development Tools${NC}"
        echo "---"

        # Check if Homebrew is installed
        if ! command -v brew &>/dev/null; then
          echo -e "${RED}Error:${NC} Homebrew is not installed"
          echo "Install from: https://brew.sh"
          exit 1
        fi

        # Install or upgrade bun
        echo -e "${GREEN}Checking bun...${NC}"
        if brew list oven-sh/bun/bun &>/dev/null; then
          echo -e "${YELLOW}Upgrading bun...${NC}"
          brew upgrade oven-sh/bun/bun
        else
          echo -e "${YELLOW}Installing bun...${NC}"
          brew install oven-sh/bun/bun
        fi

        # Install or upgrade go-task
        echo -e "${GREEN}Checking go-task...${NC}"
        if brew list go-task &>/dev/null; then
          echo -e "${YELLOW}Upgrading go-task...${NC}"
          brew upgrade go-task
        else
          echo -e "${YELLOW}Installing go-task...${NC}"
          brew install go-task
        fi

        # Install or upgrade semgrep
        echo -e "${GREEN}Checking semgrep...${NC}"
        if brew list semgrep &>/dev/null; then
          echo -e "${YELLOW}Upgrading semgrep...${NC}"
          brew upgrade semgrep
        else
          echo -e "${YELLOW}Installing semgrep...${NC}"
          brew install semgrep
        fi

        # Install project dependencies
        echo ""
        echo -e "${GREEN}Installing project dependencies...${NC}"
        bun install

        echo ""
        echo -e "${GREEN}✓${NC} All tools installed successfully"

  setup:repo:
    desc: "Configure GitHub repository secrets for CI/CD"
    aliases: [setup]
    silent: true
    cmds:
      - |
        set -euo pipefail

        GREEN='\033[0;32m'
        YELLOW='\033[0;33m'
        CYAN='\033[0;36m'
        RED='\033[0;31m'
        BOLD='\033[1m'
        NC='\033[0m'

        echo -e "${CYAN}GitHub Repository Secret Configuration${NC}"
        echo "---"

        # Required secrets for CI/CD
        SECRETS=(
          "CODECOV_TOKEN"
          "NPM_TOKEN"
          "RELEASE_BOT_APP_ID"
          "RELEASE_BOT_PRIVATE_KEY"
          "CLAUDE_CODE_OAUTH_TOKEN"
        )

        # Check gh CLI
        if ! command -v gh &>/dev/null; then
          echo -e "${RED}Error:${NC} GitHub CLI (gh) is not installed"
          echo "Install from: https://cli.github.com"
          exit 1
        fi

        # Check gh authentication — login interactively if needed
        if ! gh auth status &>/dev/null 2>&1; then
          echo -e "${YELLOW}Not logged in to GitHub. Launching login...${NC}"
          gh auth login -p ssh --skip-ssh-key
        fi

        # Ensure gh uses SSH protocol
        CURRENT_PROTO=$(gh config get git_protocol 2>/dev/null || echo "")
        if [ "$CURRENT_PROTO" != "ssh" ]; then
          gh config set git_protocol ssh
          echo -e "${GREEN}✓${NC} Set gh git_protocol to ssh"
        fi

        # Try to resolve secrets from 1Password via .env
        OP_AVAILABLE=false
        if command -v op &>/dev/null; then
          echo -e "${GREEN}1Password CLI detected${NC}"
          # Source resolved env vars if op:export task exists
          EXPORT_FILE=$(task op:export 2>/dev/null) && {
            if [ -f "$EXPORT_FILE" ]; then
              source "$EXPORT_FILE"
              OP_AVAILABLE=true
              echo -e "${GREEN}Secrets resolved from 1Password${NC}"
            fi
          } || {
            echo -e "${YELLOW}Could not resolve secrets from 1Password (task op:export failed)${NC}"
          }
        else
          echo -e "${YELLOW}1Password CLI not found — will prompt for values${NC}"
        fi

        # Prevent sourced tokens from overriding gh CLI auth
        unset GITHUB_TOKEN GH_TOKEN

        echo ""

        # Detect repo from git remote
        REPO=$(gh repo view --json nameWithOwner --jq '.nameWithOwner' 2>/dev/null)
        if [ -z "$REPO" ]; then
          echo -e "${RED}Error:${NC} Could not detect GitHub repository"
          echo "Run from inside a git repo with a GitHub remote"
          exit 1
        fi
        echo -e "Repository: ${GREEN}${REPO}${NC}"
        echo ""

        # Get existing secrets
        EXISTING=$(gh secret list --repo "$REPO" --json name --jq '.[].name' 2>/dev/null || echo "")

        CONFIGURED=0
        SKIPPED=0
        FAILED=0

        for SECRET in "${SECRETS[@]}"; do
          # Check if secret already exists
          if echo "$EXISTING" | grep -q "^${SECRET}$"; then
            echo -e "  ${GREEN}✓${NC} ${SECRET} (already configured)"
            SKIPPED=$((SKIPPED + 1))
            continue
          fi

          # Try to get value from resolved env
          VALUE="${!SECRET:-}"

          if [ -n "$VALUE" ] && [ "$VALUE" != "op://"* ]; then
            # Have a resolved value — set it
            if gh secret set "$SECRET" --repo "$REPO" --body "$VALUE"; then
              echo -e "  ${GREEN}✓${NC} ${SECRET} (set from 1Password)"
              CONFIGURED=$((CONFIGURED + 1))
            else
              echo -e "  ${RED}✗${NC} ${SECRET} (failed to set)"
              FAILED=$((FAILED + 1))
            fi
          else
            # Prompt for value interactively
            echo -e "  ${YELLOW}?${NC} ${SECRET} — no resolved value available"

            if [ "$SECRET" = "RELEASE_BOT_PRIVATE_KEY" ]; then
              echo -e "    ${CYAN}Paste PEM private key (end with empty line):${NC}"
              PEM_VALUE=""
              while IFS= read -r line; do
                [ -z "$line" ] && break
                PEM_VALUE="${PEM_VALUE}${line}"$'\n'
              done

              if [ -n "$PEM_VALUE" ]; then
                if echo "$PEM_VALUE" | gh secret set "$SECRET" --repo "$REPO"; then
                  echo -e "    ${GREEN}✓${NC} ${SECRET} (set from input)"
                  CONFIGURED=$((CONFIGURED + 1))
                else
                  echo -e "    ${RED}✗${NC} ${SECRET} (failed to set)"
                  FAILED=$((FAILED + 1))
                fi
              else
                echo -e "    ${YELLOW}⊘${NC} ${SECRET} (skipped)"
                FAILED=$((FAILED + 1))
              fi
            else
              read -rp "    Enter value (or press Enter to skip): " INPUT_VALUE
              if [ -n "$INPUT_VALUE" ]; then
                if gh secret set "$SECRET" --repo "$REPO" --body "$INPUT_VALUE"; then
                  echo -e "    ${GREEN}✓${NC} ${SECRET} (set from input)"
                  CONFIGURED=$((CONFIGURED + 1))
                else
                  echo -e "    ${RED}✗${NC} ${SECRET} (failed to set)"
                  FAILED=$((FAILED + 1))
                fi
              else
                echo -e "    ${YELLOW}⊘${NC} ${SECRET} (skipped)"
                FAILED=$((FAILED + 1))
              fi
            fi
          fi
        done

        echo ""
        echo -e "${BOLD}Summary:${NC}"
        echo -e "  Configured: ${GREEN}${CONFIGURED}${NC}"
        echo -e "  Existing:   ${YELLOW}${SKIPPED}${NC}"
        echo -e "  Remaining:  ${RED}${FAILED}${NC}"

        if [ "$FAILED" -gt 0 ]; then
          echo ""
          echo -e "${YELLOW}Re-run 'task setup:repo' after resolving remaining secrets${NC}"
        else
          echo ""
          echo -e "${GREEN}✓${NC} All repository secrets configured"
        fi

  default:
    desc: "Show available mmd tasks"
    aliases: [help, h]
    silent: true
    cmds:
      - |
        GREEN='\033[0;32m'
        YELLOW='\033[0;33m'
        BLUE='\033[0;34m'
        CYAN='\033[0;36m'
        BOLD='\033[1m'
        NC='\033[0m'

        echo -e "${BOLD}@lekman/mmd — Mermaid Diagram Management CLI${NC}"
        echo ""
        echo "Command                            Alias     Description"
        echo "────────────────────────────────────────────────────────────────────────────────"
        echo -e "${BOLD}Setup:${NC}"
        echo -e "  ${GREEN}task install${NC}                     ${YELLOW}i${NC}         Install/upgrade required tools"
        echo -e "  ${GREEN}task setup:repo${NC}                  ${YELLOW}setup${NC}     Configure GitHub repo secrets"
        echo ""
        echo -e "${BOLD}Development:${NC}"
        echo -e "  ${GREEN}task lint${NC}                        ${YELLOW}l${NC}         Run linting checks"
        echo -e "  ${GREEN}task format${NC}                      ${YELLOW}fmt${NC}       Format code"
        echo -e "  ${GREEN}task typecheck${NC}                   ${YELLOW}tc${NC}        Run TypeScript type checking"
        echo -e "  ${GREEN}task test${NC}                        ${YELLOW}t${NC}         Run tests"
        echo -e "  ${GREEN}task test:coverage${NC}               ${YELLOW}cov${NC}       Run tests with coverage report"
        echo -e "  ${GREEN}task quality${NC}                     ${YELLOW}q${NC}         Run all quality checks"
        echo -e "  ${GREEN}task run${NC}                         ${YELLOW}r${NC}         Run CLI from source"
        echo -e "  ${GREEN}task build${NC}                       ${YELLOW}b${NC}         Bundle CLI for distribution"
        echo ""
        echo -e "${BOLD}Security:${NC}"
        echo -e "  ${GREEN}task security:scan${NC}               ${YELLOW}s:s${NC}       Run semgrep security scanner"
        echo ""
        echo -e "${BOLD}Task Libraries:${NC}"
        echo -e "  ${GREEN}task git:<command>${NC}                         Git & GitHub operations"
        echo -e "  ${GREEN}task json:<command>${NC}                        JSON linting & validation"
        echo -e "  ${GREEN}task yaml:<command>${NC}              ${YELLOW}yml${NC}       YAML linting & validation"
        echo -e "  ${GREEN}task markdown:<command>${NC}          ${YELLOW}md${NC}        Markdown linting & validation"
        echo -e "  ${GREEN}task security:<command>${NC}          ${YELLOW}s${NC}         Security scanning tools"
        echo -e "  ${GREEN}task op:<command>${NC}                          1Password secret resolution"
        echo ""
        echo -e "${BLUE}Run 'task --list' to see all available tasks${NC}"

  lint:
    desc: "Run linting checks"
    aliases: [l]
    silent: true
    cmds:
      - |
        GREEN='\033[0;32m'
        NC='\033[0m'

        echo -e "${GREEN}Running linting...${NC}"
        bunx turbo run lint

  format:
    desc: "Format code"
    aliases: [fmt]
    silent: true
    cmds:
      - |
        GREEN='\033[0;32m'
        NC='\033[0m'

        echo -e "${GREEN}Formatting code...${NC}"
        bun run format

  typecheck:
    desc: "Run TypeScript type checking"
    aliases: [tc]
    silent: true
    cmds:
      - |
        GREEN='\033[0;32m'
        NC='\033[0m'

        echo -e "${GREEN}Type checking...${NC}"
        bunx turbo run typecheck

  test:
    desc: "Run tests"
    aliases: [t]
    silent: true
    cmds:
      - |
        GREEN='\033[0;32m'
        NC='\033[0m'

        echo -e "${GREEN}Running tests...${NC}"
        bunx turbo run test

  test:coverage:
    desc: "Run tests with coverage report"
    aliases: [cov]
    silent: true
    cmds:
      - |
        GREEN='\033[0;32m'
        CYAN='\033[0;36m'
        NC='\033[0m'

        echo -e "${GREEN}Running unit tests with coverage...${NC}"
        bunx turbo run test:coverage
        echo ""
        echo -e "${CYAN}Coverage report generated:${NC}"
        echo -e "  LCOV: ${GREEN}coverage/lcov.info${NC}"

  quality:
    desc: "Run all quality checks (lint, typecheck, security, test)"
    aliases: [q]
    silent: true
    cmds:
      - |
        GREEN='\033[0;32m'
        CYAN='\033[0;36m'
        NC='\033[0m'

        echo -e "${CYAN}Running Quality Checks${NC}"
        echo "---"
      - task: lint
      - task: typecheck
      - task: security:scan
      - task: test
      - |
        GREEN='\033[0;32m'
        NC='\033[0m'

        echo ""
        echo -e "${GREEN}✓${NC} All quality checks passed"

  run:
    desc: "Run CLI from source (pass args after --)"
    aliases: [r]
    silent: true
    cmds:
      - bun run src/cli/index.ts {{.CLI_ARGS}}

  test:config:
    desc: "Verify mmd config command (creates, skips, force-overwrites)"
    silent: true
    cmds:
      - |
        set -euo pipefail

        GREEN='\033[0;32m'
        RED='\033[0;31m'
        NC='\033[0m'
        PASS=0
        FAIL=0

        REPO_ROOT=$(git rev-parse --show-toplevel)
        CONFIG="$REPO_ROOT/.mermaid.json"
        BACKUP=""

        # Back up existing config
        if [ -f "$CONFIG" ]; then
          BACKUP=$(mktemp)
          cp "$CONFIG" "$BACKUP"
          rm "$CONFIG"
        fi

        cleanup() {
          if [ -n "$BACKUP" ] && [ -f "$BACKUP" ]; then
            cp "$BACKUP" "$CONFIG"
            rm "$BACKUP"
          elif [ -z "$BACKUP" ]; then
            rm -f "$CONFIG"
          fi
        }
        trap cleanup EXIT

        # Test 1: Creates config when missing
        bun run src/cli/index.ts config > /dev/null 2>&1
        if [ -f "$CONFIG" ] && grep -q '"outputDir"' "$CONFIG"; then
          echo -e "  ${GREEN}✓${NC} Creates .mermaid.json when missing"
          PASS=$((PASS + 1))
        else
          echo -e "  ${RED}✗${NC} Failed to create .mermaid.json"
          FAIL=$((FAIL + 1))
        fi

        # Test 2: Skips when already exists
        OUTPUT=$(bun run src/cli/index.ts config 2>&1)
        if echo "$OUTPUT" | grep -q "already exists"; then
          echo -e "  ${GREEN}✓${NC} Skips when .mermaid.json exists"
          PASS=$((PASS + 1))
        else
          echo -e "  ${RED}✗${NC} Did not skip existing .mermaid.json"
          FAIL=$((FAIL + 1))
        fi

        # Test 3: Overwrites with --force
        echo '{}' > "$CONFIG"
        bun run src/cli/index.ts config --force > /dev/null 2>&1
        if grep -q '"outputDir"' "$CONFIG"; then
          echo -e "  ${GREEN}✓${NC} Overwrites with --force"
          PASS=$((PASS + 1))
        else
          echo -e "  ${RED}✗${NC} Failed to overwrite with --force"
          FAIL=$((FAIL + 1))
        fi

        echo ""
        echo -e "  ${GREEN}${PASS} passed${NC}, ${RED}${FAIL} failed${NC}"
        [ "$FAIL" -eq 0 ] || exit 1

  build:
    desc: "Bundle CLI for distribution"
    aliases: [b]
    silent: true
    cmds:
      - |
        GREEN='\033[0;32m'
        NC='\033[0m'

        echo -e "${GREEN}Building CLI...${NC}"
        bun run build
        echo -e "${GREEN}✓${NC} dist/index.js built"
